### ISSUE TITLE
Would like Typescript definition file..

### ISSUE THREAD

**Issue by sjmcdowall** [oleg-koval/koa-verto#30]
Hey -- Since I use Typescript in all my projects -- can we have a .d.ts file for this?  

Or -- more specifically -- I'll do the .d.ts file and do a PR if you want .. :)

**Comment by oleg-koval** [comment]
would be great to have this

**Comment by sjmcdowall** [comment]
Submitted PR # 33

**Comment by oleg-koval** [comment]
Thanks!
